import type { Localized } from "@/lib/i18n";

export type Dispatch = {
  slug: string;
  date: string; // ISO 8601
  title: Localized<string>;
  excerpt: Localized<string>;
  readTime: string;
  body: Localized<string[]>; // paragraphs
};

export const dispatches: Dispatch[] = [
  {
    slug: "what-second-line-grc-actually-does",
    date: "2026-06-18",
    title: {
      en: "What second-line GRC actually does all day",
      fr: "Ce que fait vraiment la GRC de seconde ligne",
    },
    excerpt: {
      en: "The org chart says: frameworks, policies, oversight. The calendar says: translation. Between what a standard requires and what a warehouse can execute, somebody has to carry the meaning across.",
      fr: "L'organigramme dit : référentiels, politiques, supervision. L'agenda, lui, dit : traduction. Entre ce qu'exige une norme et ce qu'un entrepôt peut réellement appliquer, il faut bien que quelqu'un fasse passer le sens.",
    },
    readTime: "6 min",
    body: {
      en: [
        "The three-lines model reads cleanly on a slide. The first line owns the risk because it owns the operations; the second line builds the frameworks and challenges the first; the third line audits everyone. What the slide does not show is that the second line produces almost nothing that is valuable in itself. A risk analysis, a policy, a supplier assessment — none of these artefacts protect anything. They only matter if they change a decision somewhere in the first line. Which means the real job, most days, is translation: turning a control requirement into a sentence an operations manager can act on, and turning what actually happens on a logistics site into evidence a framework can recognise.",
        "EBIOS RM workshops make this concrete faster than anything else. The method is French, structured, and quietly brilliant, but its outputs are only as honest as the people in the room. Ask a site manager to enumerate feared events and you get silence; ask what would stop trucks leaving the yard tomorrow morning and you cannot make them stop talking. The methodology work is in the mapping — carrying that answer back through supporting assets, threat sources, and attack paths until it becomes a scenario the organisation can rank and treat. The insight is never in the matrix. The insight is in the conversation the matrix forced you to have.",
        "Vulnerability management from the second line is a discipline of arithmetic under disagreement. A CVSS score arrives claiming 9.8; the asset owner claims the system is unreachable from the internet; the SLA clock is already running. The temptation is to arbitrate by authority. The productive path is to arbitrate by context: what does this score become once you account for exposure, for compensating controls, for what the asset actually processes? Some criticals deflate to scheduled maintenance. Some mediums, sitting on the wrong network segment next to the wrong database, become the week's real emergency. A tracker that reflects that reasoning is worth more than a dashboard of raw scores that nobody defends in front of an auditor.",
        "The part nobody romanticises: sitewalks. Walking a logistics site with a checklist is where paper meets concrete, sometimes literally — the badge reader that has been propped open for the summer heat, the visitor register that stopped being filled in March, the server cupboard that doubles as storage for pallets of shrink-wrap. None of this appears in any tool. All of it is the actual security posture. Second-line GRC that never leaves the office converges on a beautifully documented parallel universe; the discipline is keeping the documentation tethered to the building. Policy without operational reality is assumption. I keep finding that the shortest path between the two is a pair of shoes.",
      ],
      fr: [
        "Le modèle des trois lignes de défense est limpide sur une diapositive. La première ligne porte le risque parce qu'elle porte les opérations ; la deuxième construit les référentiels et challenge la première ; la troisième audite tout le monde. Ce que la diapositive ne montre pas, c'est que la deuxième ligne ne produit presque rien qui ait de la valeur en soi. Une analyse de risques, une politique, une évaluation fournisseur : aucun de ces livrables ne protège quoi que ce soit. Ils ne comptent que s'ils changent une décision quelque part en première ligne. Le vrai métier, la plupart des jours, c'est donc de la traduction : transformer une exigence de contrôle en une phrase qu'un responsable d'exploitation peut appliquer, et transformer ce qui se passe réellement sur un site logistique en une preuve qu'un référentiel sait reconnaître.",
        "Rien ne rend cela plus concret qu'un atelier EBIOS RM. La méthode est française, structurée, discrètement brillante, mais ses livrables ne valent que ce que valent les gens autour de la table. Demandez à un chef de site d'énumérer ses événements redoutés : silence. Demandez-lui ce qui empêcherait les camions de partir demain matin : impossible de l'arrêter. Le travail méthodologique tient dans la cartographie, c'est-à-dire ramener cette réponse à travers les biens supports, les sources de menace et les chemins d'attaque, jusqu'à en faire un scénario que l'organisation peut hiérarchiser et traiter. L'enseignement n'est jamais dans la matrice. Il est dans la conversation que la matrice vous a obligé à avoir.",
        "La gestion des vulnérabilités, vue de la deuxième ligne, est une discipline d'arithmétique sous désaccord. Un score CVSS débarque en annonçant 9,8 ; le propriétaire de l'actif jure que le système est injoignable depuis Internet ; le chrono du SLA tourne déjà. La tentation, c'est d'arbitrer par l'autorité. La voie utile, c'est d'arbitrer par le contexte : que devient ce score une fois pris en compte l'exposition, les contrôles compensatoires, ce que l'actif traite réellement ? Certaines criticités se dégonflent en maintenance planifiée. Certaines vulnérabilités moyennes, posées sur le mauvais segment réseau à côté de la mauvaise base de données, deviennent la vraie urgence de la semaine. Un outil de suivi qui reflète ce raisonnement vaut plus qu'un tableau de bord de scores bruts que personne n'assume devant un auditeur.",
        "Et puis il y a la partie que personne ne romantise : les visites de site. Arpenter un entrepôt logistique avec une check-list, c'est l'endroit où le papier rencontre le béton, parfois au sens propre : le lecteur de badge calé en position ouverte à cause de la chaleur, le registre des visiteurs plus rempli depuis mars, le local serveur qui sert aussi de réserve à film plastique. Rien de tout cela ne remonte dans un outil. Tout cela constitue pourtant la posture de sécurité réelle. Une GRC de seconde ligne qui ne quitte jamais le bureau converge vers un univers parallèle magnifiquement documenté ; la discipline consiste à garder la documentation arrimée au bâtiment. Une politique sans réalité opérationnelle n'est qu'un pari. Et je continue de constater que le plus court chemin entre les deux reste une paire de chaussures.",
      ],
    },
  },
  {
    slug: "what-a-firewall-cert-actually-tests",
    date: "2026-04-09",
    title: {
      en: "What a firewall certification actually tests",
      fr: "Ce qu'une certification pare-feu teste vraiment",
    },
    excerpt: {
      en: "I passed the CSNA in March. The exam verified that I can configure a Stormshield appliance. It could not verify the thing that matters: whether a firewall run by me would still be trustworthy a year later.",
      fr: "J'ai obtenu la CSNA en mars. L'examen a vérifié que je sais configurer un boîtier Stormshield. Il ne pouvait pas vérifier l'essentiel : si un pare-feu administré par mes soins serait encore digne de confiance un an plus tard.",
    },
    readTime: "5 min",
    body: {
      en: [
        "The CSNA is an honest exam about a specific thing: can you drive a Stormshield appliance? Objects, filter policies, NAT in its several directions, IPsec tunnels, the IPS profiles and their inspection levels. Preparing for it is genuinely useful — the SNS interface stops being a wall of menus and becomes a machine whose defaults you understand and whose sharp edges you have already cut yourself on in a lab. I passed in March and the knowledge is real. But it is worth being precise about what was measured, because the industry routinely confuses it with something larger.",
        "What a certification cannot test is the lifecycle. A filter policy at minute zero is an intention; a filter policy after a year of production is an archaeology. Every rule in it was once urgent for someone. The exam asks whether you can write the rule. Operations asks the harder questions: who requested it, does it still have an owner, when does it expire, and would anyone notice if it were removed? Rule sprawl is not a configuration error — every individual rule was correct the day it shipped. It is an accumulation error, and no multiple-choice question can represent an accumulation. The difference between a certified administrator and a good one is that the second treats the rulebase as a liability to be paid down, not a text to be appended to.",
        "The second untested discipline is reading what the appliance says back. A firewall is the best-placed sensor in the building: it sees every flow that crosses a boundary, it already classifies them, and its logs are structured. Most organisations use it exclusively as an actuator — packets stop or pass — and let the sensor half run write-only into a syslog nobody queries. Studying for the IPS sections, I kept noticing how much of the value assumed someone downstream was actually looking: an inspection profile that raises alarms into a void is indistinguishable from one that is switched off. The blue-team habit of treating deny logs as telemetry, baselining them, and asking what changed this week costs nothing at purchase time and is worth more than most of what does.",
        "None of this is an argument against the certification — I would sit it again, and the discount on ego that comes from scoring 80% on a tool you thought you knew is its own education. It is an argument about what the paper attests. A certificate says: this person has seen the machine before and will not improvise the basics. Trustworthy infrastructure comes from somewhere else — from change discipline, from expiry dates on exceptions, from logs that get read. The exam is a snapshot; operating is a time series. Hiring processes that treat the first as a proxy for the second are measuring the wrong axis, and administrators who believe their own certificate are the mechanism by which good firewalls quietly go bad.",
      ],
      fr: [
        "La CSNA est un examen honnête sur un objet précis : savez-vous piloter un boîtier Stormshield ? Les objets, les politiques de filtrage, le NAT dans tous ses sens, les tunnels IPsec, les profils IPS et leurs niveaux d'inspection. La préparation est réellement utile : l'interface SNS cesse d'être un mur de menus pour devenir une machine dont on comprend les valeurs par défaut et dont on s'est déjà entaillé sur les angles vifs, en lab. Je l'ai obtenue en mars, et ces connaissances sont bien réelles. Mais il vaut la peine d'être précis sur ce qui a été mesuré, parce que le secteur confond régulièrement cette mesure avec quelque chose de plus grand.",
        "Ce qu'une certification ne peut pas tester, c'est le cycle de vie. Une politique de filtrage à la minute zéro est une intention ; la même politique après un an de production est une fouille archéologique. Chaque règle y a un jour été urgente pour quelqu'un. L'examen demande si vous savez écrire la règle. L'exploitation pose les questions plus dures : qui l'a demandée, a-t-elle encore un propriétaire, quand expire-t-elle, et quelqu'un remarquerait-il sa suppression ? L'inflation de règles n'est pas une erreur de configuration, puisque chaque règle prise isolément était juste le jour de sa mise en service. C'est une erreur d'accumulation, et aucun QCM ne sait représenter une accumulation. La différence entre un administrateur certifié et un bon administrateur, c'est que le second traite la base de règles comme une dette à rembourser, pas comme un texte à rallonger.",
        "La deuxième discipline hors examen, c'est de lire ce que le boîtier vous répond. Un pare-feu est le capteur le mieux placé du bâtiment : il voit chaque flux qui franchit une frontière, il les classe déjà, et ses journaux sont structurés. La plupart des organisations ne s'en servent que comme d'un actionneur (les paquets passent ou ne passent pas) et laissent la moitié capteur écrire dans un syslog que personne n'interroge jamais. En révisant les sections IPS, je n'arrêtais pas de le constater : une bonne part de la valeur suppose que quelqu'un, en aval, regarde vraiment. Un profil d'inspection qui lève des alertes dans le vide est indiscernable d'un profil éteint. Le réflexe blue team qui consiste à traiter les journaux de refus comme de la télémétrie, à en établir la référence et à se demander ce qui a changé cette semaine ne coûte rien à l'achat, et vaut plus que presque tout ce qui coûte.",
        "Rien de tout cela ne plaide contre la certification : je la repasserais sans hésiter, et la leçon d'humilité qu'il y a à faire 80 % sur un outil qu'on croyait connaître est une formation en soi. Cela plaide sur ce que le papier atteste. Un certificat dit : cette personne a déjà vu la machine, elle n'improvisera pas les fondamentaux. La confiance dans une infrastructure vient d'ailleurs : d'une discipline du changement, de dates d'expiration sur les exceptions, de journaux qui sont lus. L'examen est un instantané ; l'exploitation est une série temporelle. Les recrutements qui prennent le premier pour un indicateur de la seconde mesurent le mauvais axe, et les administrateurs qui croient leur propre certificat sont le mécanisme exact par lequel les bons pare-feu se dégradent en silence.",
      ],
    },
  },
  {
    slug: "on-the-fragility-of-edr-assumptions",
    date: "2025-03-14",
    title: {
      en: "On the fragility of EDR assumptions",
      fr: "Sur la fragilité des hypothèses EDR",
    },
    excerpt: {
      en: "EDR vendors sell you a dashboard. The dashboard shows what the tool caught. The data you actually need is everything it didn't.",
      fr: "Les éditeurs d'EDR vous vendent un tableau de bord. Ce tableau de bord affiche ce que l'outil a intercepté. Or, ce dont vous avez vraiment besoin, c'est tout ce qui lui a échappé.",
    },
    readTime: "6 min",
    body: {
      en: [
        "The dashboard problem in endpoint detection is a confidence problem. EDR tools surface what they detect — which is, by construction, only the set of things the vendor's research team has seen, modelled, and decided to alert on. The set of things that did not generate an alert is invisible on the dashboard. The operational reflex is to read that silence as safety. This reflex is how persistent threats persist: not because they are undetectable in principle, but because the detection infrastructure is designed to respond, not to hunt.",
        "Living-off-the-land attacks are the clearest illustration of the detection boundary. When an adversary avoids introducing new binaries and instead runs PowerShell, WMI, certutil, or bitsadmin — signed Microsoft tools doing things Microsoft tools sometimes legitimately do — the EDR heuristics face a categorisation problem with no clean answer. The behaviour is normal in some contexts and malicious in others. Distinguishing between them requires understanding what normal looks like for your specific environment: your user population, your software estate, your administration patterns. This is not something a vendor signature set knows. It is built from your own telemetry, your own baselines, and your own analysis.",
        "Clarity about what EDR purchases is an operational question, not a theological one. It is effective against commodity attacks: ransomware-as-a-service loaders that have not been custom-compiled, known malware families, stealers and droppers that behave the way malware in a sandbox behaves. It raises the cost of unsophisticated attack meaningfully. It provides endpoint telemetry that would otherwise require custom instrumentation. What it does not provide is coverage against an adversary who studied your environment before touching a keyboard — who logs in with valid credentials obtained through phishing, escalates using a legitimate vulnerability in a way that mimics normal admin behaviour, and moves carefully enough to stay below the anomaly threshold for weeks.",
        "The most useful reframe: treat EDR as the instrument that tells you the noise floor has changed. The alert tells you something deviated from baseline enough for the vendor's model to flag it. The interesting question is what happened in the period before the deviation became legible. Blue teams that wait for the dashboard to light up are always responding to day-N of an incident. Blue teams that build hypotheses about what patient adversary behaviour looks like — in their specific logs, against their specific assets, with their specific user population — have a chance at day-one or day-two detection. Assume the alert is late. Ask what the quiet period looked like and whether you would have noticed it.",
      ],
      fr: [
        "Le piège du tableau de bord, en détection sur les terminaux, est avant tout un piège de confiance. Un EDR ne remonte que ce qu'il détecte, c'est-à-dire, par construction, les seuls comportements que l'équipe de recherche de l'éditeur a déjà observés, modélisés et choisi de signaler. Tout ce qui n'a déclenché aucune alerte n'apparaît nulle part. Et le réflexe, sur le terrain, est d'interpréter ce silence comme une preuve de sécurité. C'est exactement ce réflexe qui permet aux menaces persistantes de durer : non qu'elles soient indétectables par nature, mais parce que toute l'infrastructure de détection est pensée pour réagir, jamais pour traquer.",
        "Les attaques living-off-the-land montrent mieux que tout où passe la frontière de détection. Quand un attaquant renonce à déposer ses propres binaires et se contente de PowerShell, WMI, certutil ou bitsadmin (des outils Microsoft signés, qui font des choses que les outils Microsoft font parfois tout à fait légitimement), les heuristiques de l'EDR butent sur un problème de classification sans bonne réponse. Le même comportement est anodin dans un contexte et malveillant dans un autre. Pour les départager, il faut savoir à quoi ressemble la normalité chez vous : vos utilisateurs, votre parc applicatif, vos habitudes d'administration. Aucun jeu de signatures vendu par un éditeur ne possède cette connaissance. Elle se bâtit à partir de votre propre télémétrie, de vos propres références, de votre propre analyse.",
        "Savoir précisément ce qu'on achète avec un EDR relève de l'opérationnel, pas de la théologie. Il fait son travail contre les attaques de masse : les loaders ransomware-as-a-service non recompilés sur mesure, les familles de malwares connues, les stealers et les droppers qui se comportent en sandbox comme on attend d'un malware. Il renchérit nettement le coût des attaques peu sophistiquées. Il offre une télémétrie des terminaux qu'il faudrait sinon instrumenter à la main. Ce qu'il n'offre pas, c'est une protection contre l'adversaire qui a étudié votre environnement avant même de poser les mains sur un clavier : celui qui ouvre une session avec des identifiants valides récupérés par hameçonnage, qui élève ses privilèges via une vulnérabilité légitime en imitant les gestes d'un administrateur, et qui avance assez prudemment pour passer sous le seuil d'anomalie pendant des semaines.",
        "Le bon angle, le plus utile : voir l'EDR comme l'instrument qui vous prévient que le bruit de fond a bougé. L'alerte signale qu'un événement s'est écarté de la référence au point de franchir le seuil du modèle de l'éditeur. Toute la question intéressante porte sur ce qui s'est joué avant que cet écart ne devienne lisible. Une blue team qui attend que le tableau de bord s'allume réagit toujours au jour N d'un incident. Celle qui se forge des hypothèses sur la manière dont se comporte un adversaire patient, dans ses propres journaux, contre ses propres actifs, au sein de sa propre population d'utilisateurs, se donne une chance de détecter dès le premier ou le deuxième jour. Partez du principe que l'alerte arrive en retard. Demandez-vous à quoi ressemblait la phase silencieuse, et si vous l'auriez seulement remarquée.",
      ],
    },
  },
  {
    slug: "zero-trust-is-a-posture-not-a-product",
    date: "2025-01-28",
    title: {
      en: "Zero Trust is a posture, not a product",
      fr: "Le Zero Trust est une posture, pas un produit",
    },
    excerpt: {
      en: "Buying a Zero Trust product does not move you toward the condition the phrase describes. Seventeen vendors will tell you otherwise.",
      fr: "Acheter un produit Zero Trust ne vous rapproche en rien de l'état que l'expression désigne. Dix-sept éditeurs vous jureront le contraire.",
    },
    readTime: "8 min",
    body: {
      en: [
        "The phrase Zero Trust has been almost entirely consumed by the market. It appears on product pages for firewalls, network monitors, identity platforms, microsegmentation tools, and endpoint agents — each vendor implying that purchasing their product advances the organisation toward the state the phrase describes. It does not work this way. The phrase describes an architectural and organisational posture. It cannot be purchased. It can only be built, slowly, across teams, through decisions about where verification happens and what trust boundaries mean, at a cost that does not appear on a vendor invoice.",
        "John Kindervag's 2010 Forrester research described a philosophy, not a product category: never trust, always verify. Move the trust boundary away from the network perimeter — which is porous, assumed-secure by convention, and historically incorrect — to the individual transaction. Every access request must be authenticated, authorised, and evaluated in context. The network is not the security boundary. The identity, the device posture, the request context, and the data sensitivity together constitute the boundary, dynamically, per-request. This model is sound and demanding. It requires knowing what you are protecting, who should have access to it, and what legitimate access patterns look like. Most organisations do not have this knowledge in a form precise enough to enforce it consistently.",
        "Implementing Zero Trust in a real environment surfaces three requirements that no vendor adequately prices into their sales cycle. First: a complete and maintained asset inventory, because dynamic access controls applied to assets you have not enumerated produce unpredictable results, not security. Second: identity infrastructure mature enough to provide meaningful context at access time — device health, network location, time of day, role, session risk score — and act on it consistently across all access paths, including the legacy applications that cannot participate in modern authentication flows. Third: monitoring capable of detecting anomalous access patterns in a model where everything is, by design, potentially reachable, and where anomalous must be defined against your baseline, not a generic industry threat model. None of these capabilities come in a box. All of them require organisational maturity that accumulates over years.",
        "The gap between the marketing deck and the threat model is where breaches live. Organisations that purchased the product and called it done typically retained the implicit trust assumptions of their old network architecture while adding the operational complexity of a new control plane. The organisations that have implemented the posture correctly do not describe it as an achievement. They describe it as a discipline they practise continuously — reviewing access decisions, tightening over-provisioned identities, re-evaluating what the trust model from six months ago was actually assuming about the world. Zero Trust as a destination is a narrative that serves vendors. Zero Trust as a practice is a different and more demanding commitment.",
      ],
      fr: [
        "L'expression Zero Trust a été presque entièrement digérée par le marché. On la retrouve sur les fiches produit des pare-feu, des sondes réseau, des plateformes d'identité, des outils de microsegmentation et des agents de terminaux, chaque éditeur sous-entendant qu'acheter sa solution fait avancer l'organisation vers l'état que l'expression désigne. Ce n'est pas ainsi que les choses se passent. Le Zero Trust désigne une posture, à la fois architecturale et organisationnelle. Il ne s'achète pas. Il se construit, lentement, d'une équipe à l'autre, à travers des choix sur le lieu où s'opère la vérification et sur le sens des frontières de confiance, à un coût qui ne figure sur aucune facture d'éditeur.",
        "Les travaux menés par John Kindervag chez Forrester en 2010 décrivaient une philosophie, pas une famille de produits : ne jamais faire confiance, toujours vérifier. Faire reculer la frontière de confiance, depuis le périmètre réseau (poreux, réputé sûr par habitude et démenti par l'histoire) jusqu'à la transaction elle-même. Toute demande d'accès doit être authentifiée, autorisée et évaluée dans son contexte. La frontière de sécurité, ce n'est pas le réseau. Ce sont l'identité, la posture de l'appareil, le contexte de la requête et la sensibilité des données qui, ensemble, la dessinent, de façon dynamique, requête après requête. Ce modèle est solide, et il est exigeant. Il suppose de savoir ce que l'on protège, qui doit y accéder et à quoi ressemble un accès légitime. Peu d'organisations possèdent ce savoir sous une forme assez précise pour l'appliquer de bout en bout.",
        "Déployer le Zero Trust dans un environnement réel révèle trois prérequis qu'aucun éditeur ne chiffre honnêtement dans son cycle de vente. D'abord, un inventaire des actifs complet et tenu à jour : des contrôles d'accès dynamiques appliqués à des actifs que vous n'avez jamais recensés ne produisent pas de la sécurité, mais des résultats imprévisibles. Ensuite, une infrastructure d'identité assez mature pour fournir un contexte exploitable au moment de l'accès (état de santé de l'appareil, emplacement réseau, heure, rôle, score de risque de la session) et pour en tirer les conséquences partout, sur tous les chemins d'accès, y compris les applications héritées incapables de prendre part aux flux d'authentification modernes. Enfin, une supervision capable de repérer les accès anormaux dans un modèle où tout est, par construction, potentiellement accessible, et où la notion d'anomalie se définit par rapport à votre référence, pas à un modèle de menace générique sorti d'un livre blanc sectoriel. Aucune de ces capacités ne se livre clé en main. Toutes reposent sur une maturité organisationnelle qui se gagne au fil des années.",
        "C'est dans l'écart entre l'argumentaire commercial et le modèle de menace que se logent les compromissions. Les organisations qui ont acheté le produit et coché la case s'en sont en général tirées avec les hypothèses de confiance implicites de leur ancienne architecture réseau, augmentées de la complexité d'un nouveau plan de contrôle. Celles qui ont vraiment adopté la posture ne la présentent jamais comme un trophée. Elles en parlent comme d'une discipline qu'elles entretiennent en permanence : revoir les décisions d'accès, resserrer les identités trop dotées en privilèges, réinterroger ce que le modèle de confiance d'il y a six mois tenait pour acquis du monde réel. Le Zero Trust vu comme une ligne d'arrivée, c'est un récit qui arrange les éditeurs. Le Zero Trust vu comme une pratique, c'est un engagement tout autre, et bien plus exigeant.",
      ],
    },
  },
  {
    slug: "what-side-channel-attacks-taught-me-about-patience",
    date: "2024-11-07",
    title: {
      en: "What side-channel attacks taught me about patience",
      fr: "Ce que les attaques par canal auxiliaire m'ont appris sur la patience",
    },
    excerpt: {
      en: "The first 300 traces produced a uniform noise floor. The next 4,500 produced a key. The difference was not more data.",
      fr: "Les 300 premières traces n'ont donné qu'un bruit de fond uniforme. Les 4 500 suivantes ont donné une clé. Et ce n'est pas la quantité de données qui a fait la différence.",
    },
    readTime: "5 min",
    body: {
      en: [
        "The first correlation attack I ran did not work. The correlation coefficients were nearly uniform across all 256 key hypotheses for every byte position. I spent most of a day re-reading the ChipWhisperer documentation, then another half-day examining the trigger logic, before I measured the actual problem: the shunt resistor I had soldered into the VCC line was too high in resistance, and the resulting voltage drop was saturating the oscilloscope input on high-activity clock cycles. The signal I was trying to recover was buried under clipping artifacts. The mathematics were correct. The experiment was broken at the level of the physics, and I had spent two days debugging the wrong layer.",
        "What followed was a structured debugging process that has stayed with me. One variable at a time. Characterise the noise floor before touching the analysis. Understand your instrumentation before trusting your data. Lower-resistance shunt. Reduce the oscilloscope input voltage range. Capture a single trace and inspect it visually: does the power waveform have the morphology you would expect from an AES round structure? Does the trigger fire at the right point in the encryption? Does the capture window cover the operation you are targeting? Only when the answers to those questions are clearly yes should you collect traces at scale. The correct sequence is: understand your measurement first, then apply your model. Most of the time wasted in experimental work comes from reversing that order.",
        "The attack that recovered the full 128-bit AES key in 4,800 traces was methodical rather than clever. The insight was not mathematical — Correlation Power Analysis is well-documented and the implementation is straightforward once your measurement is clean. The insight was operational: the failure was not a data quantity problem, it was a data quality problem. Adding more traces against a broken measurement setup does not converge on a result. It produces a larger, equally useless dataset. This distinction matters and is consistently underweighted in how we talk about both offensive techniques and defensive practices. The bottleneck is almost always what you are measuring and how, not how much of it you have collected.",
        "The transfer to threat hunting is direct and underappreciated. Hunting for persistent activity in an environment is structurally similar to recovering a key from noisy power measurements: you have a hypothesis, you have imperfect data, and the temptation is to run the analysis immediately. The analysts who consistently find what others miss are not the ones with the most sophisticated detection logic. They are the ones who, before starting, understood their data sources — coverage gaps, log forwarding latency, timestamp normalisation, what is indexed in the SIEM versus what is collected but unqueried, which hosts produce no telemetry at all. Patience, in both contexts, is methodology operating at a pace slower than the problem seems to demand. It is also the only approach that reliably works.",
      ],
      fr: [
        "Ma première attaque par corrélation a échoué. Les coefficients de corrélation restaient quasi uniformes sur les 256 hypothèses de clé, et ce pour chaque position d'octet. J'ai passé presque une journée à éplucher la documentation de ChipWhisperer, puis une demi-journée encore à scruter la logique de déclenchement, avant de mettre le doigt sur le vrai problème : la résistance de shunt que j'avais soudée sur la ligne VCC était trop élevée, et la chute de tension qu'elle provoquait saturait l'entrée de l'oscilloscope sur les cycles d'horloge les plus chargés. Le signal que je voulais récupérer disparaissait sous les artefacts d'écrêtage. Les maths étaient justes. C'est la physique du montage qui clochait, et j'avais passé deux jours à déboguer la mauvaise couche.",
        "S'en est suivie une démarche de débogage méthodique qui ne m'a plus quitté. Une variable à la fois. Caractériser le bruit de fond avant de toucher à l'analyse. Comprendre son instrumentation avant d'accorder la moindre confiance à ses données. Un shunt moins résistif. Resserrer la plage de tension en entrée de l'oscilloscope. Capturer une seule trace et l'examiner à l'œil : la courbe de consommation a-t-elle bien la morphologie attendue d'une ronde AES ? Le déclenchement tombe-t-il au bon instant du chiffrement ? La fenêtre de capture englobe-t-elle vraiment l'opération visée ? Ce n'est qu'une fois ces réponses franchement affirmatives qu'on peut se permettre de collecter des traces à grande échelle. Le bon ordre, c'est : d'abord comprendre sa mesure, ensuite appliquer son modèle. L'essentiel du temps gaspillé en expérimentation vient de l'inversion de ces deux étapes.",
        "L'attaque qui a finalement récupéré la clé AES de 128 bits en intégralité, en 4 800 traces, devait tout à la méthode et rien au génie. L'idée décisive n'avait rien de mathématique : la Correlation Power Analysis est bien documentée et son implémentation va de soi dès lors que la mesure est propre. L'idée décisive était opérationnelle : l'échec ne tenait pas à un manque de données, mais à leur qualité. Empiler des traces sur un montage de mesure bancal ne converge sur rien du tout. On récolte seulement un jeu de données plus gros, et tout aussi inexploitable. La nuance est capitale, et on la sous-estime constamment, qu'on parle de techniques offensives ou de pratiques défensives. Le goulot d'étranglement, c'est presque toujours ce que l'on mesure et comment, jamais le volume que l'on a accumulé.",
        "Le parallèle avec la traque des menaces est direct, et trop rarement relevé. Chercher une activité persistante dans un environnement ressemble en tout point à récupérer une clé dans des mesures de consommation bruitées : vous avez une hypothèse, vous avez des données imparfaites, et la tentation est de vous jeter sur l'analyse tout de suite. Les analystes qui débusquent régulièrement ce que les autres laissent passer ne sont pas ceux qui manient la logique de détection la plus sophistiquée. Ce sont ceux qui, avant de commencer, ont pris le temps de connaître leurs sources : trous de couverture, latence d'acheminement des journaux, normalisation des horodatages, ce que le SIEM indexe par rapport à ce qu'il collecte sans jamais l'interroger, et les hôtes qui ne remontent absolument aucune télémétrie. Dans les deux mondes, la patience n'est rien d'autre qu'une méthode qui avance plus lentement que le problème ne semble l'exiger. C'est aussi la seule qui finit toujours par payer.",
      ],
    },
  },
];

// Adjacent dispatch helper for navigation.
export function getAdjacentDispatch(
  slug: string
): { prev: Dispatch | null; next: Dispatch | null } {
  const idx = dispatches.findIndex((d) => d.slug === slug);
  return {
    prev: idx > 0 ? dispatches[idx - 1] : null,
    next: idx < dispatches.length - 1 ? dispatches[idx + 1] : null,
  };
}
