import type { Localized } from "@/lib/i18n";

export type Dispatch = {
  slug: string;
  date: string; // ISO 8601
  title: Localized<string>;
  excerpt: Localized<string>;
  readTime: string;
  body: Localized<string[]>; // paragraphs
};

export const dispatches: Dispatch[] = [
  {
    slug: "on-the-fragility-of-edr-assumptions",
    date: "2025-03-14",
    title: {
      en: "On the fragility of EDR assumptions",
      fr: "Sur la fragilité des hypothèses EDR",
    },
    excerpt: {
      en: "EDR vendors sell you a dashboard. The dashboard shows what the tool caught. The data you actually need is everything it didn't.",
      fr: "Les éditeurs d'EDR vous vendent un tableau de bord. Ce tableau de bord affiche ce que l'outil a intercepté. Or, ce dont vous avez vraiment besoin, c'est tout ce qui lui a échappé.",
    },
    readTime: "6 min",
    body: {
      en: [
        "The dashboard problem in endpoint detection is a confidence problem. EDR tools surface what they detect — which is, by construction, only the set of things the vendor's research team has seen, modelled, and decided to alert on. The set of things that did not generate an alert is invisible on the dashboard. The operational reflex is to read that silence as safety. This reflex is how persistent threats persist: not because they are undetectable in principle, but because the detection infrastructure is designed to respond, not to hunt.",
        "Living-off-the-land attacks are the clearest illustration of the detection boundary. When an adversary avoids introducing new binaries and instead runs PowerShell, WMI, certutil, or bitsadmin — signed Microsoft tools doing things Microsoft tools sometimes legitimately do — the EDR heuristics face a categorisation problem with no clean answer. The behaviour is normal in some contexts and malicious in others. Distinguishing between them requires understanding what normal looks like for your specific environment: your user population, your software estate, your administration patterns. This is not something a vendor signature set knows. It is built from your own telemetry, your own baselines, and your own analysis.",
        "Clarity about what EDR purchases is an operational question, not a theological one. It is effective against commodity attacks: ransomware-as-a-service loaders that have not been custom-compiled, known malware families, stealers and droppers that behave the way malware in a sandbox behaves. It raises the cost of unsophisticated attack meaningfully. It provides endpoint telemetry that would otherwise require custom instrumentation. What it does not provide is coverage against an adversary who studied your environment before touching a keyboard — who logs in with valid credentials obtained through phishing, escalates using a legitimate vulnerability in a way that mimics normal admin behaviour, and moves carefully enough to stay below the anomaly threshold for weeks.",
        "The most useful reframe: treat EDR as the instrument that tells you the noise floor has changed. The alert tells you something deviated from baseline enough for the vendor's model to flag it. The interesting question is what happened in the period before the deviation became legible. Blue teams that wait for the dashboard to light up are always responding to day-N of an incident. Blue teams that build hypotheses about what patient adversary behaviour looks like — in their specific logs, against their specific assets, with their specific user population — have a chance at day-one or day-two detection. Assume the alert is late. Ask what the quiet period looked like and whether you would have noticed it.",
      ],
      fr: [
        "Le piège du tableau de bord, en détection sur les terminaux, est avant tout un piège de confiance. Un EDR ne remonte que ce qu'il détecte, c'est-à-dire, par construction, les seuls comportements que l'équipe de recherche de l'éditeur a déjà observés, modélisés et choisi de signaler. Tout ce qui n'a déclenché aucune alerte n'apparaît nulle part. Et le réflexe, sur le terrain, est d'interpréter ce silence comme une preuve de sécurité. C'est exactement ce réflexe qui permet aux menaces persistantes de durer : non qu'elles soient indétectables par nature, mais parce que toute l'infrastructure de détection est pensée pour réagir, jamais pour traquer.",
        "Les attaques living-off-the-land montrent mieux que tout où passe la frontière de détection. Quand un attaquant renonce à déposer ses propres binaires et se contente de PowerShell, WMI, certutil ou bitsadmin (des outils Microsoft signés, qui font des choses que les outils Microsoft font parfois tout à fait légitimement), les heuristiques de l'EDR butent sur un problème de classification sans bonne réponse. Le même comportement est anodin dans un contexte et malveillant dans un autre. Pour les départager, il faut savoir à quoi ressemble la normalité chez vous : vos utilisateurs, votre parc applicatif, vos habitudes d'administration. Aucun jeu de signatures vendu par un éditeur ne possède cette connaissance. Elle se bâtit à partir de votre propre télémétrie, de vos propres références, de votre propre analyse.",
        "Savoir précisément ce qu'on achète avec un EDR relève de l'opérationnel, pas de la théologie. Il fait son travail contre les attaques de masse : les loaders ransomware-as-a-service non recompilés sur mesure, les familles de malwares connues, les stealers et les droppers qui se comportent en sandbox comme on attend d'un malware. Il renchérit nettement le coût des attaques peu sophistiquées. Il offre une télémétrie des terminaux qu'il faudrait sinon instrumenter à la main. Ce qu'il n'offre pas, c'est une protection contre l'adversaire qui a étudié votre environnement avant même de poser les mains sur un clavier : celui qui ouvre une session avec des identifiants valides récupérés par hameçonnage, qui élève ses privilèges via une vulnérabilité légitime en imitant les gestes d'un administrateur, et qui avance assez prudemment pour passer sous le seuil d'anomalie pendant des semaines.",
        "Le bon angle, le plus utile : voir l'EDR comme l'instrument qui vous prévient que le bruit de fond a bougé. L'alerte signale qu'un événement s'est écarté de la référence au point de franchir le seuil du modèle de l'éditeur. Toute la question intéressante porte sur ce qui s'est joué avant que cet écart ne devienne lisible. Une blue team qui attend que le tableau de bord s'allume réagit toujours au jour N d'un incident. Celle qui se forge des hypothèses sur la manière dont se comporte un adversaire patient, dans ses propres journaux, contre ses propres actifs, au sein de sa propre population d'utilisateurs, se donne une chance de détecter dès le premier ou le deuxième jour. Partez du principe que l'alerte arrive en retard. Demandez-vous à quoi ressemblait la phase silencieuse, et si vous l'auriez seulement remarquée.",
      ],
    },
  },
  {
    slug: "zero-trust-is-a-posture-not-a-product",
    date: "2025-01-28",
    title: {
      en: "Zero Trust is a posture, not a product",
      fr: "Le Zero Trust est une posture, pas un produit",
    },
    excerpt: {
      en: "Buying a Zero Trust product does not move you toward the condition the phrase describes. Seventeen vendors will tell you otherwise.",
      fr: "Acheter un produit Zero Trust ne vous rapproche en rien de l'état que l'expression désigne. Dix-sept éditeurs vous jureront le contraire.",
    },
    readTime: "8 min",
    body: {
      en: [
        "The phrase Zero Trust has been almost entirely consumed by the market. It appears on product pages for firewalls, network monitors, identity platforms, microsegmentation tools, and endpoint agents — each vendor implying that purchasing their product advances the organisation toward the state the phrase describes. It does not work this way. The phrase describes an architectural and organisational posture. It cannot be purchased. It can only be built, slowly, across teams, through decisions about where verification happens and what trust boundaries mean, at a cost that does not appear on a vendor invoice.",
        "John Kindervag's 2010 Forrester research described a philosophy, not a product category: never trust, always verify. Move the trust boundary away from the network perimeter — which is porous, assumed-secure by convention, and historically incorrect — to the individual transaction. Every access request must be authenticated, authorised, and evaluated in context. The network is not the security boundary. The identity, the device posture, the request context, and the data sensitivity together constitute the boundary, dynamically, per-request. This model is sound and demanding. It requires knowing what you are protecting, who should have access to it, and what legitimate access patterns look like. Most organisations do not have this knowledge in a form precise enough to enforce it consistently.",
        "Implementing Zero Trust in a real environment surfaces three requirements that no vendor adequately prices into their sales cycle. First: a complete and maintained asset inventory, because dynamic access controls applied to assets you have not enumerated produce unpredictable results, not security. Second: identity infrastructure mature enough to provide meaningful context at access time — device health, network location, time of day, role, session risk score — and act on it consistently across all access paths, including the legacy applications that cannot participate in modern authentication flows. Third: monitoring capable of detecting anomalous access patterns in a model where everything is, by design, potentially reachable, and where anomalous must be defined against your baseline, not a generic industry threat model. None of these capabilities come in a box. All of them require organisational maturity that accumulates over years.",
        "The gap between the marketing deck and the threat model is where breaches live. Organisations that purchased the product and called it done typically retained the implicit trust assumptions of their old network architecture while adding the operational complexity of a new control plane. The organisations that have implemented the posture correctly do not describe it as an achievement. They describe it as a discipline they practise continuously — reviewing access decisions, tightening over-provisioned identities, re-evaluating what the trust model from six months ago was actually assuming about the world. Zero Trust as a destination is a narrative that serves vendors. Zero Trust as a practice is a different and more demanding commitment.",
      ],
      fr: [
        "L'expression Zero Trust a été presque entièrement digérée par le marché. On la retrouve sur les fiches produit des pare-feu, des sondes réseau, des plateformes d'identité, des outils de microsegmentation et des agents de terminaux, chaque éditeur sous-entendant qu'acheter sa solution fait avancer l'organisation vers l'état que l'expression désigne. Ce n'est pas ainsi que les choses se passent. Le Zero Trust désigne une posture, à la fois architecturale et organisationnelle. Il ne s'achète pas. Il se construit, lentement, d'une équipe à l'autre, à travers des choix sur le lieu où s'opère la vérification et sur le sens des frontières de confiance, à un coût qui ne figure sur aucune facture d'éditeur.",
        "Les travaux menés par John Kindervag chez Forrester en 2010 décrivaient une philosophie, pas une famille de produits : ne jamais faire confiance, toujours vérifier. Faire reculer la frontière de confiance, depuis le périmètre réseau (poreux, réputé sûr par habitude et démenti par l'histoire) jusqu'à la transaction elle-même. Toute demande d'accès doit être authentifiée, autorisée et évaluée dans son contexte. La frontière de sécurité, ce n'est pas le réseau. Ce sont l'identité, la posture de l'appareil, le contexte de la requête et la sensibilité des données qui, ensemble, la dessinent, de façon dynamique, requête après requête. Ce modèle est solide, et il est exigeant. Il suppose de savoir ce que l'on protège, qui doit y accéder et à quoi ressemble un accès légitime. Peu d'organisations possèdent ce savoir sous une forme assez précise pour l'appliquer de bout en bout.",
        "Déployer le Zero Trust dans un environnement réel révèle trois prérequis qu'aucun éditeur ne chiffre honnêtement dans son cycle de vente. D'abord, un inventaire des actifs complet et tenu à jour : des contrôles d'accès dynamiques appliqués à des actifs que vous n'avez jamais recensés ne produisent pas de la sécurité, mais des résultats imprévisibles. Ensuite, une infrastructure d'identité assez mature pour fournir un contexte exploitable au moment de l'accès (état de santé de l'appareil, emplacement réseau, heure, rôle, score de risque de la session) et pour en tirer les conséquences partout, sur tous les chemins d'accès, y compris les applications héritées incapables de prendre part aux flux d'authentification modernes. Enfin, une supervision capable de repérer les accès anormaux dans un modèle où tout est, par construction, potentiellement accessible, et où la notion d'anomalie se définit par rapport à votre référence, pas à un modèle de menace générique sorti d'un livre blanc sectoriel. Aucune de ces capacités ne se livre clé en main. Toutes reposent sur une maturité organisationnelle qui se gagne au fil des années.",
        "C'est dans l'écart entre l'argumentaire commercial et le modèle de menace que se logent les compromissions. Les organisations qui ont acheté le produit et coché la case s'en sont en général tirées avec les hypothèses de confiance implicites de leur ancienne architecture réseau, augmentées de la complexité d'un nouveau plan de contrôle. Celles qui ont vraiment adopté la posture ne la présentent jamais comme un trophée. Elles en parlent comme d'une discipline qu'elles entretiennent en permanence : revoir les décisions d'accès, resserrer les identités trop dotées en privilèges, réinterroger ce que le modèle de confiance d'il y a six mois tenait pour acquis du monde réel. Le Zero Trust vu comme une ligne d'arrivée, c'est un récit qui arrange les éditeurs. Le Zero Trust vu comme une pratique, c'est un engagement tout autre, et bien plus exigeant.",
      ],
    },
  },
  {
    slug: "what-side-channel-attacks-taught-me-about-patience",
    date: "2024-11-07",
    title: {
      en: "What side-channel attacks taught me about patience",
      fr: "Ce que les attaques par canal auxiliaire m'ont appris sur la patience",
    },
    excerpt: {
      en: "The first 300 traces produced a uniform noise floor. The next 4,500 produced a key. The difference was not more data.",
      fr: "Les 300 premières traces n'ont donné qu'un bruit de fond uniforme. Les 4 500 suivantes ont donné une clé. Et ce n'est pas la quantité de données qui a fait la différence.",
    },
    readTime: "5 min",
    body: {
      en: [
        "The first correlation attack I ran did not work. The correlation coefficients were nearly uniform across all 256 key hypotheses for every byte position. I spent most of a day re-reading the ChipWhisperer documentation, then another half-day examining the trigger logic, before I measured the actual problem: the shunt resistor I had soldered into the VCC line was too high in resistance, and the resulting voltage drop was saturating the oscilloscope input on high-activity clock cycles. The signal I was trying to recover was buried under clipping artifacts. The mathematics were correct. The experiment was broken at the level of the physics, and I had spent two days debugging the wrong layer.",
        "What followed was a structured debugging process that has stayed with me. One variable at a time. Characterise the noise floor before touching the analysis. Understand your instrumentation before trusting your data. Lower-resistance shunt. Reduce the oscilloscope input voltage range. Capture a single trace and inspect it visually: does the power waveform have the morphology you would expect from an AES round structure? Does the trigger fire at the right point in the encryption? Does the capture window cover the operation you are targeting? Only when the answers to those questions are clearly yes should you collect traces at scale. The correct sequence is: understand your measurement first, then apply your model. Most of the time wasted in experimental work comes from reversing that order.",
        "The attack that recovered the full 128-bit AES key in 4,800 traces was methodical rather than clever. The insight was not mathematical — Correlation Power Analysis is well-documented and the implementation is straightforward once your measurement is clean. The insight was operational: the failure was not a data quantity problem, it was a data quality problem. Adding more traces against a broken measurement setup does not converge on a result. It produces a larger, equally useless dataset. This distinction matters and is consistently underweighted in how we talk about both offensive techniques and defensive practices. The bottleneck is almost always what you are measuring and how, not how much of it you have collected.",
        "The transfer to threat hunting is direct and underappreciated. Hunting for persistent activity in an environment is structurally similar to recovering a key from noisy power measurements: you have a hypothesis, you have imperfect data, and the temptation is to run the analysis immediately. The analysts who consistently find what others miss are not the ones with the most sophisticated detection logic. They are the ones who, before starting, understood their data sources — coverage gaps, log forwarding latency, timestamp normalisation, what is indexed in the SIEM versus what is collected but unqueried, which hosts produce no telemetry at all. Patience, in both contexts, is methodology operating at a pace slower than the problem seems to demand. It is also the only approach that reliably works.",
      ],
      fr: [
        "Ma première attaque par corrélation a échoué. Les coefficients de corrélation restaient quasi uniformes sur les 256 hypothèses de clé, et ce pour chaque position d'octet. J'ai passé presque une journée à éplucher la documentation de ChipWhisperer, puis une demi-journée encore à scruter la logique de déclenchement, avant de mettre le doigt sur le vrai problème : la résistance de shunt que j'avais soudée sur la ligne VCC était trop élevée, et la chute de tension qu'elle provoquait saturait l'entrée de l'oscilloscope sur les cycles d'horloge les plus chargés. Le signal que je voulais récupérer disparaissait sous les artefacts d'écrêtage. Les maths étaient justes. C'est la physique du montage qui clochait, et j'avais passé deux jours à déboguer la mauvaise couche.",
        "S'en est suivie une démarche de débogage méthodique qui ne m'a plus quitté. Une variable à la fois. Caractériser le bruit de fond avant de toucher à l'analyse. Comprendre son instrumentation avant d'accorder la moindre confiance à ses données. Un shunt moins résistif. Resserrer la plage de tension en entrée de l'oscilloscope. Capturer une seule trace et l'examiner à l'œil : la courbe de consommation a-t-elle bien la morphologie attendue d'une ronde AES ? Le déclenchement tombe-t-il au bon instant du chiffrement ? La fenêtre de capture englobe-t-elle vraiment l'opération visée ? Ce n'est qu'une fois ces réponses franchement affirmatives qu'on peut se permettre de collecter des traces à grande échelle. Le bon ordre, c'est : d'abord comprendre sa mesure, ensuite appliquer son modèle. L'essentiel du temps gaspillé en expérimentation vient de l'inversion de ces deux étapes.",
        "L'attaque qui a finalement récupéré la clé AES de 128 bits en intégralité, en 4 800 traces, devait tout à la méthode et rien au génie. L'idée décisive n'avait rien de mathématique : la Correlation Power Analysis est bien documentée et son implémentation va de soi dès lors que la mesure est propre. L'idée décisive était opérationnelle : l'échec ne tenait pas à un manque de données, mais à leur qualité. Empiler des traces sur un montage de mesure bancal ne converge sur rien du tout. On récolte seulement un jeu de données plus gros, et tout aussi inexploitable. La nuance est capitale, et on la sous-estime constamment, qu'on parle de techniques offensives ou de pratiques défensives. Le goulot d'étranglement, c'est presque toujours ce que l'on mesure et comment, jamais le volume que l'on a accumulé.",
        "Le parallèle avec la traque des menaces est direct, et trop rarement relevé. Chercher une activité persistante dans un environnement ressemble en tout point à récupérer une clé dans des mesures de consommation bruitées : vous avez une hypothèse, vous avez des données imparfaites, et la tentation est de vous jeter sur l'analyse tout de suite. Les analystes qui débusquent régulièrement ce que les autres laissent passer ne sont pas ceux qui manient la logique de détection la plus sophistiquée. Ce sont ceux qui, avant de commencer, ont pris le temps de connaître leurs sources : trous de couverture, latence d'acheminement des journaux, normalisation des horodatages, ce que le SIEM indexe par rapport à ce qu'il collecte sans jamais l'interroger, et les hôtes qui ne remontent absolument aucune télémétrie. Dans les deux mondes, la patience n'est rien d'autre qu'une méthode qui avance plus lentement que le problème ne semble l'exiger. C'est aussi la seule qui finit toujours par payer.",
      ],
    },
  },
];

// Adjacent dispatch helper for navigation.
export function getAdjacentDispatch(
  slug: string
): { prev: Dispatch | null; next: Dispatch | null } {
  const idx = dispatches.findIndex((d) => d.slug === slug);
  return {
    prev: idx > 0 ? dispatches[idx - 1] : null,
    next: idx < dispatches.length - 1 ? dispatches[idx + 1] : null,
  };
}
