import type { Localized } from "@/lib/i18n";

export type Dispatch = {
  slug: string;
  date: string; // ISO 8601
  title: Localized<string>;
  excerpt: Localized<string>;
  readTime: string;
  body: Localized<string[]>; // paragraphs
};

export const dispatches: Dispatch[] = [
  {
    slug: "on-the-fragility-of-edr-assumptions",
    date: "2025-03-14",
    title: {
      en: "On the fragility of EDR assumptions",
      fr: "Sur la fragilité des hypothèses EDR",
    },
    excerpt: {
      en: "EDR vendors sell you a dashboard. The dashboard shows what the tool caught. The data you actually need is everything it didn't.",
      fr: "Les éditeurs d'EDR vous vendent un tableau de bord. Le tableau de bord montre ce que l'outil a intercepté. Les données dont vous avez réellement besoin sont tout ce qu'il n'a pas intercepté.",
    },
    readTime: "6 min",
    body: {
      en: [
        "The dashboard problem in endpoint detection is a confidence problem. EDR tools surface what they detect — which is, by construction, only the set of things the vendor's research team has seen, modelled, and decided to alert on. The set of things that did not generate an alert is invisible on the dashboard. The operational reflex is to read that silence as safety. This reflex is how persistent threats persist: not because they are undetectable in principle, but because the detection infrastructure is designed to respond, not to hunt.",
        "Living-off-the-land attacks are the clearest illustration of the detection boundary. When an adversary avoids introducing new binaries and instead runs PowerShell, WMI, certutil, or bitsadmin — signed Microsoft tools doing things Microsoft tools sometimes legitimately do — the EDR heuristics face a categorisation problem with no clean answer. The behaviour is normal in some contexts and malicious in others. Distinguishing between them requires understanding what normal looks like for your specific environment: your user population, your software estate, your administration patterns. This is not something a vendor signature set knows. It is built from your own telemetry, your own baselines, and your own analysis.",
        "Clarity about what EDR purchases is an operational question, not a theological one. It is effective against commodity attacks: ransomware-as-a-service loaders that have not been custom-compiled, known malware families, stealers and droppers that behave the way malware in a sandbox behaves. It raises the cost of unsophisticated attack meaningfully. It provides endpoint telemetry that would otherwise require custom instrumentation. What it does not provide is coverage against an adversary who studied your environment before touching a keyboard — who logs in with valid credentials obtained through phishing, escalates using a legitimate vulnerability in a way that mimics normal admin behaviour, and moves carefully enough to stay below the anomaly threshold for weeks.",
        "The most useful reframe: treat EDR as the instrument that tells you the noise floor has changed. The alert tells you something deviated from baseline enough for the vendor's model to flag it. The interesting question is what happened in the period before the deviation became legible. Blue teams that wait for the dashboard to light up are always responding to day-N of an incident. Blue teams that build hypotheses about what patient adversary behaviour looks like — in their specific logs, against their specific assets, with their specific user population — have a chance at day-one or day-two detection. Assume the alert is late. Ask what the quiet period looked like and whether you would have noticed it.",
      ],
      fr: [
        "Le problème du tableau de bord dans la détection sur les terminaux est un problème de confiance. Les outils EDR font remonter ce qu'ils détectent, c'est-à-dire, par construction, uniquement l'ensemble des éléments que l'équipe de recherche de l'éditeur a observés, modélisés et décidé de signaler. L'ensemble des éléments qui n'ont déclenché aucune alerte reste invisible sur le tableau de bord. Le réflexe opérationnel consiste à lire ce silence comme un gage de sécurité. Ce réflexe est précisément la raison pour laquelle les menaces persistantes persistent : non parce qu'elles sont indétectables en principe, mais parce que l'infrastructure de détection est conçue pour réagir, pas pour traquer.",
        "Les attaques living-off-the-land constituent l'illustration la plus nette de la frontière de détection. Lorsqu'un adversaire évite d'introduire de nouveaux binaires et exécute à la place PowerShell, WMI, certutil ou bitsadmin (des outils Microsoft signés accomplissant des actions que les outils Microsoft accomplissent parfois légitimement), les heuristiques de l'EDR se heurtent à un problème de catégorisation sans réponse claire. Le comportement est normal dans certains contextes et malveillant dans d'autres. Les distinguer suppose de comprendre à quoi ressemble la normalité pour votre environnement spécifique : votre population d'utilisateurs, votre parc logiciel, vos schémas d'administration. Ce n'est pas une chose que connaît un jeu de signatures fourni par un éditeur. Cela se construit à partir de votre propre télémétrie, de vos propres références et de votre propre analyse.",
        "Avoir une vision claire de ce que l'on achète avec un EDR est une question opérationnelle, pas une question théologique. Il est efficace contre les attaques de masse : les loaders ransomware-as-a-service qui n'ont pas été compilés sur mesure, les familles de malwares connues, les stealers et droppers qui se comportent comme un malware se comporte dans une sandbox. Il augmente sensiblement le coût des attaques peu sophistiquées. Il fournit une télémétrie des terminaux qui exigerait autrement une instrumentation sur mesure. Ce qu'il ne fournit pas, c'est une couverture face à un adversaire qui a étudié votre environnement avant même de toucher un clavier : qui se connecte avec des identifiants valides obtenus par hameçonnage, élève ses privilèges en exploitant une vulnérabilité légitime d'une manière qui imite le comportement normal d'un administrateur, et se déplace avec assez de prudence pour rester sous le seuil d'anomalie pendant des semaines.",
        "Le recadrage le plus utile : considérer l'EDR comme l'instrument qui vous indique que le bruit de fond a changé. L'alerte vous signale que quelque chose s'est suffisamment écarté de la référence pour que le modèle de l'éditeur le signale. La question intéressante est de savoir ce qui s'est passé durant la période précédant le moment où l'écart est devenu lisible. Les blue teams qui attendent que le tableau de bord s'allume réagissent toujours au jour N d'un incident. Les blue teams qui élaborent des hypothèses sur ce à quoi ressemble le comportement d'un adversaire patient (dans leurs journaux spécifiques, contre leurs actifs spécifiques, avec leur population d'utilisateurs spécifique) ont une chance de détecter au premier ou au deuxième jour. Partez du principe que l'alerte est tardive. Demandez-vous à quoi ressemblait la période de calme et si vous l'auriez remarquée.",
      ],
    },
  },
  {
    slug: "zero-trust-is-a-posture-not-a-product",
    date: "2025-01-28",
    title: {
      en: "Zero Trust is a posture, not a product",
      fr: "Le Zero Trust est une posture, pas un produit",
    },
    excerpt: {
      en: "Buying a Zero Trust product does not move you toward the condition the phrase describes. Seventeen vendors will tell you otherwise.",
      fr: "Acheter un produit Zero Trust ne vous rapproche pas de l'état que l'expression décrit. Dix-sept éditeurs vous diront le contraire.",
    },
    readTime: "8 min",
    body: {
      en: [
        "The phrase Zero Trust has been almost entirely consumed by the market. It appears on product pages for firewalls, network monitors, identity platforms, microsegmentation tools, and endpoint agents — each vendor implying that purchasing their product advances the organisation toward the state the phrase describes. It does not work this way. The phrase describes an architectural and organisational posture. It cannot be purchased. It can only be built, slowly, across teams, through decisions about where verification happens and what trust boundaries mean, at a cost that does not appear on a vendor invoice.",
        "John Kindervag's 2010 Forrester research described a philosophy, not a product category: never trust, always verify. Move the trust boundary away from the network perimeter — which is porous, assumed-secure by convention, and historically incorrect — to the individual transaction. Every access request must be authenticated, authorised, and evaluated in context. The network is not the security boundary. The identity, the device posture, the request context, and the data sensitivity together constitute the boundary, dynamically, per-request. This model is sound and demanding. It requires knowing what you are protecting, who should have access to it, and what legitimate access patterns look like. Most organisations do not have this knowledge in a form precise enough to enforce it consistently.",
        "Implementing Zero Trust in a real environment surfaces three requirements that no vendor adequately prices into their sales cycle. First: a complete and maintained asset inventory, because dynamic access controls applied to assets you have not enumerated produce unpredictable results, not security. Second: identity infrastructure mature enough to provide meaningful context at access time — device health, network location, time of day, role, session risk score — and act on it consistently across all access paths, including the legacy applications that cannot participate in modern authentication flows. Third: monitoring capable of detecting anomalous access patterns in a model where everything is, by design, potentially reachable, and where anomalous must be defined against your baseline, not a generic industry threat model. None of these capabilities come in a box. All of them require organisational maturity that accumulates over years.",
        "The gap between the marketing deck and the threat model is where breaches live. Organisations that purchased the product and called it done typically retained the implicit trust assumptions of their old network architecture while adding the operational complexity of a new control plane. The organisations that have implemented the posture correctly do not describe it as an achievement. They describe it as a discipline they practise continuously — reviewing access decisions, tightening over-provisioned identities, re-evaluating what the trust model from six months ago was actually assuming about the world. Zero Trust as a destination is a narrative that serves vendors. Zero Trust as a practice is a different and more demanding commitment.",
      ],
      fr: [
        "L'expression Zero Trust a été presque entièrement absorbée par le marché. Elle figure sur les pages produit des pare-feu, des sondes réseau, des plateformes d'identité, des outils de microsegmentation et des agents de terminaux : chaque éditeur laissant entendre que l'achat de son produit fait progresser l'organisation vers l'état que l'expression décrit. Cela ne fonctionne pas ainsi. L'expression désigne une posture architecturale et organisationnelle. Elle ne s'achète pas. Elle se construit uniquement, lentement, à travers les équipes, au moyen de décisions sur l'endroit où la vérification a lieu et sur ce que signifient les frontières de confiance, à un coût qui ne figure sur aucune facture d'éditeur.",
        "Les travaux de John Kindervag pour Forrester en 2010 décrivaient une philosophie, pas une catégorie de produits : ne jamais faire confiance, toujours vérifier. Déplacer la frontière de confiance loin du périmètre réseau (poreux, supposé sûr par convention et historiquement erroné) jusqu'à la transaction individuelle. Toute demande d'accès doit être authentifiée, autorisée et évaluée en contexte. Le réseau n'est pas la frontière de sécurité. L'identité, la posture de l'appareil, le contexte de la requête et la sensibilité des données constituent ensemble la frontière, de manière dynamique, requête par requête. Ce modèle est solide et exigeant. Il suppose de savoir ce que l'on protège, qui devrait y avoir accès et à quoi ressemblent les schémas d'accès légitimes. La plupart des organisations ne possèdent pas cette connaissance sous une forme assez précise pour l'appliquer de façon cohérente.",
        "Mettre en œuvre le Zero Trust dans un environnement réel fait apparaître trois exigences qu'aucun éditeur n'intègre correctement au prix de son cycle de vente. Premièrement : un inventaire des actifs complet et maintenu, car des contrôles d'accès dynamiques appliqués à des actifs que vous n'avez pas recensés produisent des résultats imprévisibles, pas de la sécurité. Deuxièmement : une infrastructure d'identité assez mature pour fournir un contexte significatif au moment de l'accès (état de santé de l'appareil, localisation réseau, heure de la journée, rôle, score de risque de session) et pour agir en conséquence de façon cohérente sur tous les chemins d'accès, y compris les applications héritées incapables de participer aux flux d'authentification modernes. Troisièmement : une surveillance capable de détecter des schémas d'accès anormaux dans un modèle où tout est, par conception, potentiellement accessible, et où la notion d'anomalie doit être définie par rapport à votre référence, pas à un modèle de menace générique du secteur. Aucune de ces capacités ne se livre clé en main. Toutes exigent une maturité organisationnelle qui s'accumule au fil des années.",
        "L'écart entre la présentation commerciale et le modèle de menace est l'espace où vivent les compromissions. Les organisations qui ont acheté le produit et considéré la tâche accomplie ont généralement conservé les hypothèses de confiance implicites de leur ancienne architecture réseau, tout en ajoutant la complexité opérationnelle d'un nouveau plan de contrôle. Les organisations qui ont correctement mis en œuvre la posture ne la décrivent pas comme un accomplissement. Elles la décrivent comme une discipline qu'elles pratiquent en continu : révision des décisions d'accès, resserrement des identités surdotées en privilèges, réévaluation de ce que le modèle de confiance d'il y a six mois supposait réellement du monde. Le Zero Trust en tant que destination est un récit qui sert les éditeurs. Le Zero Trust en tant que pratique est un engagement différent et plus exigeant.",
      ],
    },
  },
  {
    slug: "what-side-channel-attacks-taught-me-about-patience",
    date: "2024-11-07",
    title: {
      en: "What side-channel attacks taught me about patience",
      fr: "Ce que les attaques par canal auxiliaire m'ont appris sur la patience",
    },
    excerpt: {
      en: "The first 300 traces produced a uniform noise floor. The next 4,500 produced a key. The difference was not more data.",
      fr: "Les 300 premières traces n'ont produit qu'un bruit de fond uniforme. Les 4 500 suivantes ont produit une clé. La différence ne tenait pas à un surcroît de données.",
    },
    readTime: "5 min",
    body: {
      en: [
        "The first correlation attack I ran did not work. The correlation coefficients were nearly uniform across all 256 key hypotheses for every byte position. I spent most of a day re-reading the ChipWhisperer documentation, then another half-day examining the trigger logic, before I measured the actual problem: the shunt resistor I had soldered into the VCC line was too high in resistance, and the resulting voltage drop was saturating the oscilloscope input on high-activity clock cycles. The signal I was trying to recover was buried under clipping artifacts. The mathematics were correct. The experiment was broken at the level of the physics, and I had spent two days debugging the wrong layer.",
        "What followed was a structured debugging process that has stayed with me. One variable at a time. Characterise the noise floor before touching the analysis. Understand your instrumentation before trusting your data. Lower-resistance shunt. Reduce the oscilloscope input voltage range. Capture a single trace and inspect it visually: does the power waveform have the morphology you would expect from an AES round structure? Does the trigger fire at the right point in the encryption? Does the capture window cover the operation you are targeting? Only when the answers to those questions are clearly yes should you collect traces at scale. The correct sequence is: understand your measurement first, then apply your model. Most of the time wasted in experimental work comes from reversing that order.",
        "The attack that recovered the full 128-bit AES key in 4,800 traces was methodical rather than clever. The insight was not mathematical — Correlation Power Analysis is well-documented and the implementation is straightforward once your measurement is clean. The insight was operational: the failure was not a data quantity problem, it was a data quality problem. Adding more traces against a broken measurement setup does not converge on a result. It produces a larger, equally useless dataset. This distinction matters and is consistently underweighted in how we talk about both offensive techniques and defensive practices. The bottleneck is almost always what you are measuring and how, not how much of it you have collected.",
        "The transfer to threat hunting is direct and underappreciated. Hunting for persistent activity in an environment is structurally similar to recovering a key from noisy power measurements: you have a hypothesis, you have imperfect data, and the temptation is to run the analysis immediately. The analysts who consistently find what others miss are not the ones with the most sophisticated detection logic. They are the ones who, before starting, understood their data sources — coverage gaps, log forwarding latency, timestamp normalisation, what is indexed in the SIEM versus what is collected but unqueried, which hosts produce no telemetry at all. Patience, in both contexts, is methodology operating at a pace slower than the problem seems to demand. It is also the only approach that reliably works.",
      ],
      fr: [
        "La première attaque par corrélation que j'ai menée n'a pas fonctionné. Les coefficients de corrélation étaient quasi uniformes sur les 256 hypothèses de clé pour chaque position d'octet. J'ai passé presque une journée à relire la documentation de ChipWhisperer, puis une demi-journée de plus à examiner la logique de déclenchement, avant de mesurer le véritable problème : la résistance de shunt que j'avais soudée sur la ligne VCC avait une résistance trop élevée, et la chute de tension qui en résultait saturait l'entrée de l'oscilloscope sur les cycles d'horloge à forte activité. Le signal que je cherchais à récupérer était enseveli sous des artefacts d'écrêtage. Les mathématiques étaient correctes. L'expérience était défaillante au niveau de la physique, et j'avais passé deux jours à déboguer la mauvaise couche.",
        "Ce qui a suivi fut un processus de débogage structuré qui m'est resté. Une variable à la fois. Caractériser le bruit de fond avant de toucher à l'analyse. Comprendre son instrumentation avant de faire confiance à ses données. Shunt de résistance plus faible. Réduire la plage de tension d'entrée de l'oscilloscope. Capturer une seule trace et l'inspecter visuellement : la forme d'onde de consommation présente-t-elle la morphologie que l'on attendrait d'une structure de tour AES ? Le déclencheur se déclenche-t-il au bon moment du chiffrement ? La fenêtre de capture couvre-t-elle l'opération que l'on vise ? Ce n'est que lorsque la réponse à ces questions est clairement oui que l'on devrait collecter des traces à grande échelle. La séquence correcte est la suivante : comprendre sa mesure d'abord, puis appliquer son modèle. La plus grande partie du temps perdu dans le travail expérimental provient de l'inversion de cet ordre.",
        "L'attaque qui a récupéré l'intégralité de la clé AES de 128 bits en 4 800 traces relevait de la méthode plus que de l'ingéniosité. L'idée déterminante n'était pas mathématique : la Correlation Power Analysis est bien documentée et sa mise en œuvre est simple dès lors que la mesure est propre. L'idée déterminante était opérationnelle : l'échec n'était pas un problème de quantité de données, c'était un problème de qualité des données. Ajouter davantage de traces sur un montage de mesure défaillant ne converge vers aucun résultat. Cela produit un jeu de données plus volumineux et tout aussi inutile. Cette distinction compte et reste systématiquement sous-estimée dans notre façon de parler tant des techniques offensives que des pratiques défensives. Le goulot d'étranglement est presque toujours ce que l'on mesure et comment, pas la quantité que l'on en a collectée.",
        "Le transfert vers la traque des menaces est direct et trop peu apprécié. Traquer une activité persistante dans un environnement est structurellement comparable à la récupération d'une clé à partir de mesures de consommation bruitées : vous avez une hypothèse, vous avez des données imparfaites, et la tentation est de lancer l'analyse immédiatement. Les analystes qui trouvent régulièrement ce que les autres manquent ne sont pas ceux dotés de la logique de détection la plus sophistiquée. Ce sont ceux qui, avant de commencer, ont compris leurs sources de données : lacunes de couverture, latence de transfert des journaux, normalisation des horodatages, ce qui est indexé dans le SIEM par rapport à ce qui est collecté mais jamais interrogé, et quels hôtes ne produisent aucune télémétrie. La patience, dans les deux contextes, est une méthodologie qui opère à un rythme plus lent que celui que le problème semble exiger. C'est aussi la seule approche qui fonctionne de manière fiable.",
      ],
    },
  },
];

// Adjacent dispatch helper for navigation.
export function getAdjacentDispatch(
  slug: string
): { prev: Dispatch | null; next: Dispatch | null } {
  const idx = dispatches.findIndex((d) => d.slug === slug);
  return {
    prev: idx > 0 ? dispatches[idx - 1] : null,
    next: idx < dispatches.length - 1 ? dispatches[idx + 1] : null,
  };
}
